/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootlayoutImport } from './routes/_root_layout'
import { Route as RootlayoutIndexImport } from './routes/_root_layout/index'
import { Route as RootlayoutAboutImport } from './routes/_root_layout/about'

// Create/Update Routes

const RootlayoutRoute = RootlayoutImport.update({
  id: '/_root_layout',
  getParentRoute: () => rootRoute,
} as any)

const RootlayoutIndexRoute = RootlayoutIndexImport.update({
  path: '/',
  getParentRoute: () => RootlayoutRoute,
} as any)

const RootlayoutAboutRoute = RootlayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => RootlayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root_layout': {
      id: '/_root_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_root_layout/about': {
      id: '/_root_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootlayoutAboutImport
      parentRoute: typeof RootlayoutImport
    }
    '/_root_layout/': {
      id: '/_root_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootlayoutIndexImport
      parentRoute: typeof RootlayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  RootlayoutRoute: RootlayoutRoute.addChildren({
    RootlayoutAboutRoute,
    RootlayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_root_layout"
      ]
    },
    "/_root_layout": {
      "filePath": "_root_layout.tsx",
      "children": [
        "/_root_layout/about",
        "/_root_layout/"
      ]
    },
    "/_root_layout/about": {
      "filePath": "_root_layout/about.tsx",
      "parent": "/_root_layout"
    },
    "/_root_layout/": {
      "filePath": "_root_layout/index.tsx",
      "parent": "/_root_layout"
    }
  }
}
ROUTE_MANIFEST_END */
