version: "3.8"

volumes:
  fastapi_keycloak_boilerplate_pg_data:
  fastapi_keycloak_boilerplate_kc_data:

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      - fastapi_keycloak_boilerplate_kc_data:/opt/keycloak/data/
    restart: always
    ports:
      - "8080:8080"
    command: ["start-dev"]

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    volumes:
      - fastapi_keycloak_boilerplate_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
