version: "3.8"

volumes:
  fastapi_boilerplate_pg_data:
  fastapi_boilerplate_kc_data:

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      - fastapi_boilerplate_kc_data:/opt/keycloak/data/
    restart: always
    ports:
      - "8080:8080"

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    volumes:
      - fastapi_boilerplate_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
