volumes:
  fastapi_vanilla_pg_data:

services:
  fastapi_vanilla_postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    command: postgres
    volumes:
      - fastapi_vanilla_pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  fastapi_vanilla_web:
    build: ./api
    command: [
      uvicorn, app.main:app, 
      --reload, 
      --workers=1,
      --host=0.0.0.0,
      --port=8000,
      --log-config=./app/src/api_core/logging/logging_config.json,
      --log-level=info
    ]
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8004:8000
    environment:
      # General Application settings
      - PROJECT_NAME="FastAPI Vanilla BOILERPLATE"
      - BACKEND_CORS_ORIGINS="http://localhost:5173"
      - ENVIRONMENT=dev
      - TESTING=0
      # Database settings
      - POSTGRES_SERVER_URL=postgresql+asyncpg://test:test@fastapi_vanilla_postgres:5432/app_dev
      - POSTGRES_SERVER_TEST_URL=postgresql+asyncpg://test:test@fastapi_vanilla_postgres:5432/app_test
      - POSTGRES_SERVER_HOST=fastapi_vanilla_postgres
      - POSTGRES_SERVER_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test